export const SET_SELECTED_PAPER_RECORD = 'SET_SELECTED_PAPER_RECORD';

export const SET_BOOK_DIMENSIONS = 'SET_BOOK_DIMENSIONS';

export const SET_ARRANGEMENT_FINDER_LABEL = 'SET_ARRANGEMENT_FINDER_LABEL';